## **Analisando Arquivos de DO**

In [1]:
import pandas as pd

df = pd.read_parquet('/home/jamilsonfs/airflow/dags/SIM/tmp/PARQUET/DOPB2021.parquet')
df

,Tipo de Óbito,Data do Óbito,Hora do Óbito,Naturalidade,Data de Nascimento,Idade,Sexo,Raça/Cor,Estado Civil,Escolaridade,...,DTCONINV,FONTES,TPRESGINFO,TPNIVELINV,NUDIASINF,DTCADINF,MORTEPARTO,DTCONCASO,FONTESINF,ALTCAUSA
0,Não Fetal,16082021,1130,825,06061920,101 anos,Homem,Parda,Viúvo,Nenhuma,...,,,,,,,,,,
1,Não Fetal,25022021,0840,825,11011961,60 anos,Mulher,Parda,Casado,,...,,,,,,,,,,
2,Não Fetal,01032021,1615,825,01011935,86 anos,Homem,Parda,Solteito,,...,,,,,,,,,,
3,Não Fetal,03032021,1400,825,12051976,44 anos,Homem,Branca,Solteito,4 a 7 anos,...,,,,,,,,,,
4,Não Fetal,12032021,2100,825,04101972,48 anos,Mulher,Parda,Solteito,8 a 11 anos,...,29032021,,,M,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34673,Não Fetal,11072021,0220,825,26021974,47 anos,Homem,Parda,Casado,8 a 11 anos,...,,,,,,,,,,
34674,Não Fetal,10072021,1640,825,02071929,92 anos,Mulher,Parda,Solteito,Nenhuma,...,,,,,,,,,,
34675,Não Fetal,10072021,1635,825,17021947,74 anos,Homem,Parda,Viúvo,1 a 3 anos,...,,,,,,,,,,
34676,Não Fetal,11072021,0245,825,13121967,53 anos,Mulher,Parda,Solteito,8 a 11 anos,...,,,,,,,,,,
34677,Não Fetal,06072021,0316,825,29121946,74 anos,Mulher,Branca,Casado,4 a 7 anos,...,,,,,,,,,,

In [11]:
df['CAUSABAS']

0           Outras Doenças Pulmonares Obstrutivas Crônicas
1                    Diabetes Mellitus Insulino-dependente
2                                        Leucemia Mielóide
3                               Infarto Agudo do Miocárdio
4        Doenças Por Vírus, de Localização Não Especifi...
                               ...
34673          Outras Doenças Isquêmicas Agudas do Coração
34674          Outras Doenças Isquêmicas Agudas do Coração
34675                         Doença Cardíaca Hipertensiva
34676                   Diabetes Mellitus Não Especificado
34677                Outras Doenças Vasculares Periféricas
Name: CAUSABAS, Length: 34678, dtype: object