In [1]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("LerDeltaFile") \
    .config("spark.jars", "/path/to/jars/delta-core_2.12-3.0.0.jar") \
    .getOrCreate()

your 131072x1 screen size is bogus. expect trouble
24/10/02 10:26:55 WARN Utils: Your hostname, LAPTOP-NDHI6BI3 resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
24/10/02 10:26:55 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
24/10/02 10:26:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/10/02 10:26:57 WARN DependencyUtils: Local jar /path/to/jars/delta-core_2.12-3.0.0.jar does not exist, skipping.
24/10/02 10:26:57 INFO SparkContext: Running Spark version 3.5.1
24/10/02 10:26:57 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
24/10/02 10:26:57 INFO SparkContext: Java version 1.8.0_422
24/10/02 10:26:57 INFO ResourceUtils: ==============================================================
24/10/02 10:26:57 INFO ResourceUtils: No custom resources configured for spark.driver.
24/10/02 10:26:57 INFO ResourceUtils: ==============================================================
24/10/02 10:26:57 INFO SparkContext: Submitted application: LerDeltaFile
24/10/02 10:26:57 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
24/10/02 10:26:57 INFO ResourceProfile: Limiting resource is cpu
24/10/02 10:26:57 INFO ResourceProfileManager: Added ResourceProfile id: 0
24/10/02 10:26:57 INFO SecurityManager: Changing view acls to: jamilsonfs
24/10/02 10:26:57 INFO SecurityManager: Changing modify acls to: jamilsonfs
24/10/02 10:26:57 INFO SecurityManager: Changing view acls groups to:
24/10/02 10:26:57 INFO SecurityManager: Changing modify acls groups to:
24/10/02 10:26:57 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: jamilsonfs; groups with view permissions: EMPTY; users with modify permissions: jamilsonfs; groups with modify permissions: EMPTY
24/10/02 10:26:58 INFO Utils: Successfully started service 'sparkDriver' on port 42389.
24/10/02 10:26:58 INFO SparkEnv: Registering MapOutputTracker
24/10/02 10:26:58 INFO SparkEnv: Registering BlockManagerMaster
24/10/02 10:26:58 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
24/10/02 10:26:58 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
24/10/02 10:26:58 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
24/10/02 10:26:58 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-98f8571b-fa5e-4ff1-b3db-4e7146c188b8
24/10/02 10:26:58 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
24/10/02 10:26:58 INFO SparkEnv: Registering OutputCommitCoordinator
24/10/02 10:26:58 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
24/10/02 10:26:59 INFO Utils: Successfully started service 'SparkUI' on port 4040.
24/10/02 10:26:59 ERROR SparkContext: Failed to add /path/to/jars/delta-core_2.12-3.0.0.jar to Spark environment
java.io.FileNotFoundException: Jar /path/to/jars/delta-core_2.12-3.0.0.jar not found
	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:2100)
	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2156)
	at org.apache.spark.SparkContext.$anonfun$new$15(SparkContext.scala:526)
	at org.apache.spark.SparkContext.$anonfun$new$15$adapted(SparkContext.scala:526)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:526)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Thread.java:750)
24/10/02 10:26:59 INFO Executor: Starting executor ID driver on host 10.255.255.254
24/10/02 10:26:59 INFO Executor: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
24/10/02 10:26:59 INFO Executor: Java version 1.8.0_422
24/10/02 10:26:59 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
24/10/02 10:26:59 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@fb20bbe for default.
24/10/02 10:26:59 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36849.
24/10/02 10:26:59 INFO NettyBlockTransferService: Server created on 10.255.255.254:36849
24/10/02 10:26:59 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
24/10/02 10:26:59 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.255.255.254, 36849, None)
24/10/02 10:26:59 INFO BlockManagerMasterEndpoint: Registering block manager 10.255.255.254:36849 with 366.3 MiB RAM, BlockManagerId(driver, 10.255.255.254, 36849, None)
24/10/02 10:26:59 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.255.255.254, 36849, None)
24/10/02 10:26:59 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.255.255.254, 36849, None)

In [2]:
import pyarrow.parquet as pq
import os

directory = "/home/jamilsonfs/airflow/dags/SIA/tmp/DELTA/ACFPB2101.delta/"

parquet_files = [os.path.join(directory, f) for f in os.listdir(directory) if f.endswith('.parquet')]

dataset = pq.ParquetDataset(parquet_files)
table = dataset.read()


df = table.to_pandas()
display(df)

,ACF_ARTDIA,ACF_DUPLEX,ACF_FLEBIT,ACF_FREMIT,ACF_HEMATO,ACF_PREFAV,ACF_PULSO,ACF_USOCAT,ACF_VEIAVI,ACF_VEIDIA,...,AP_RACACOR,AP_SEXO,AP_TPAPAC,AP_TPUPS,AP_TRANSF,AP_UFDIF,AP_UFMUN,AP_UFNACIO,AP_UNISOL,AP_VL_AP
0,3,S,S,3,S,S,S,S,S,3,...,Branca,Masculino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,251080,010,2605473,600.0
1,3,S,S,3,S,S,S,S,S,3,...,Branca,Masculino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,251080,010,2605473,600.0
2,3,S,S,3,S,S,S,S,S,3,...,Branca,Masculino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,251080,010,2605473,600.0
3,3,S,S,3,S,S,S,S,S,3,...,Branca,Masculino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,251080,010,2605473,600.0
4,3,S,S,3,S,S,S,S,S,3,...,Branca,Masculino,Unica,36,NÃ£o,Mesmo UF do estabelecimento,250370,010,7939906,600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2,N,N,2,N,N,N,N,N,2,...,Amarela,Masculino,Unica,36,NÃ£o,Mesmo UF do estabelecimento,250750,010,2341417,600.0
58,0001,N,N,1,N,N,S,N,N,0001,...,Amarela,Feminino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,250750,010,0000000,600.0
59,0001,N,N,1,N,N,S,N,N,0001,...,Amarela,Masculino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,250750,010,0000000,600.0
60,0001,N,N,1,N,N,S,N,N,0001,...,Amarela,Masculino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,250750,010,0000000,600.0
61,0001,N,N,1,N,N,S,N,N,0001,...,Amarela,Feminino,Unica,05,NÃ£o,Mesmo UF do estabelecimento,250750,010,0000000,600.0

In [3]:
df.columns

Index(['ACF_ARTDIA', 'ACF_DUPLEX', 'ACF_FLEBIT', 'ACF_FREMIT', 'ACF_HEMATO',
       'ACF_PREFAV', 'ACF_PULSO', 'ACF_USOCAT', 'ACF_VEIAVI', 'ACF_VEIDIA',
       'AP_ALTA', 'AP_APACANT', 'AP_AUTORIZ', 'AP_CATEND', 'AP_CEPPCN',
       'AP_CIDCAS', 'AP_CIDPRI', 'AP_CIDSEC', 'AP_CMP', 'AP_CNPJCPF',
       'AP_CNPJMNT', 'AP_CODEMI', 'AP_CODUNI', 'AP_COIDADE', 'AP_CONDIC',
       'AP_DTAUT', 'AP_DTFIM', 'AP_DTINIC', 'AP_DTOCOR', 'AP_DTSOLIC',
       'AP_ENCERR', 'AP_GESTAO', 'AP_MN_IND', 'AP_MOTSAI', 'AP_MUNPCN',
       'AP_NATJUR', 'AP_NUIDADE', 'AP_OBITO', 'AP_PERMAN', 'AP_PRIPAL',
       'AP_RACACOR', 'AP_SEXO', 'AP_TPAPAC', 'AP_TPUPS', 'AP_TRANSF',
       'AP_UFDIF', 'AP_UFMUN', 'AP_UFNACIO', 'AP_UNISOL', 'AP_VL_AP'],
      dtype='object')

RD

In [7]:
import pyarrow.parquet as pq
import os

directory = "/home/jamilsonfs/airflow/dags/SIH/tmp/DELTA/RDPB2201.delta/RDPB2101.delta"

parquet_files = [os.path.join(directory, f) for f in os.listdir(directory) if f.endswith('.parquet')]

dataset = pq.ParquetDataset(parquet_files)
table = dataset.read()


df = table.to_pandas()
display(df)

,UF_ZI,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,SEXO,UTI_MES_TO,...,DIAGSEC5,DIAGSEC6,DIAGSEC7,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7
0,250000,03,,2521150120820,1,58900000,250370,19611206,1,0,...,,,,1,0,0,0,0,0,0
1,250000,03,,2521150120830,1,58935000,250330,19670703,1,0,...,,,,0,0,0,0,0,0,0
2,250000,03,,2521150120841,1,58900000,250370,19721108,3,0,...,,,,0,0,0,0,0,0,0
3,250000,03,,2521150120852,1,58908000,251207,20030425,3,0,...,,,,0,0,0,0,0,0,0
4,250000,03,,2521150120863,1,58960000,250240,19831113,3,0,...,,,,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13139,251600,07,08778268001051,2521101757515,1,21630000,330455,20190729,3,0,...,,,,0,0,0,0,0,0,0
13140,251600,07,08778268001051,2521101757614,1,58220000,250150,20081118,1,0,...,,,,0,0,0,0,0,0,0
13141,251600,07,08778268001051,2521101757658,1,58225000,251600,20020828,1,0,...,,,,0,0,0,0,0,0,0
13142,251600,07,08778268001051,2521101757900,1,58225000,251600,20170316,1,0,...,,,,0,0,0,0,0,0,0
13143,251600,07,08778268001051,2521101757911,1,58225000,251600,20150122,3,0,...,,,,0,0,0,0,0,0,0

In [8]:
df.columns

Index(['UF_ZI', 'ESPEC', 'CGC_HOSP', 'N_AIH', 'IDENT', 'CEP', 'MUNIC_RES',
       'NASC', 'SEXO', 'UTI_MES_TO', 'MARCA_UTI', 'UTI_INT_TO', 'DIAR_ACOM',
       'QT_DIARIAS', 'PROC_SOLIC', 'PROC_REA', 'VAL_SH', 'VAL_SP', 'VAL_TOT',
       'VAL_UTI', 'US_TOT', 'DT_INTER', 'DT_SAIDA', 'DIAG_PRINC', 'COBRANCA',
       'NAT_JUR', 'GESTAO', 'IND_VDRL', 'MUNIC_MOV', 'COD_IDADE', 'IDADE',
       'DIAS_PERM', 'MORTE', 'NACIONAL', 'CAR_INT', 'HOMONIMO', 'NUM_FILHOS',
       'INSTRU', 'CID_NOTIF', 'CONTRACEP1', 'CONTRACEP2', 'GESTRISCO',
       'INSC_PN', 'SEQ_AIH5', 'CBOR', 'CNAER', 'VINCPREV', 'GESTOR_COD',
       'GESTOR_TP', 'GESTOR_CPF', 'CNES', 'CNPJ_MANT', 'COMPLEX', 'FINANC',
       'FAEC_TP', 'REGCT', 'RACA_COR', 'ETNIA', 'SEQUENCIA', 'REMESSA',
       'AUD_JUST', 'SIS_JUST', 'VAL_SH_FED', 'VAL_SP_FED', 'VAL_UCI',
       'MARCA_UCI', 'DIAGSEC1', 'DIAGSEC2', 'DIAGSEC3', 'DIAGSEC4', 'DIAGSEC5',
       'DIAGSEC6', 'DIAGSEC7', 'TPDISEC1', 'TPDISEC2', 'TPDISEC3', 'TPDISEC4',
       'TPDISEC5', 'TPDISEC6', 'TPDISEC7'],
      dtype='object')

In [9]:
df['CID_NOTIF']

0
1
2
3
4
        ..
13139
13140
13141
13142
13143
Name: CID_NOTIF, Length: 13144, dtype: object